# 8. Decorators and metaclasses (numpy) — homework

In [2]:
import numpy as np

### Exercise 8.1

Create the following NumPy arrays:

(a) float from 0.0 to 1.0 step 0.1, shape=(11,),

In [20]:
a = np.linspace(0.0, 0.1, 11)

print(f'The array a\n{a}\nof shape {a.shape} and data type {a.dtype}')


The array a
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
of shape (11,) and data type float64


(b) int zeros (1 byte) with shape=(5,6),

In [19]:
b = np.zeros((5,6), dtype='int8')

print(f'The array b\n{b}\nof shape {b.shape} and data type {b.dtype}')

The array b
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
of shape (5, 6) and data type int8


(c) complex with shape=(9,), powers of x = complex(0, 1): 1, x, x\**2, ..., x\**8. 

In [27]:
c = np.array(complex(0,1)) ** np.arange(9)

print(f'The array c\n{c}\nof shape {c.shape} and data type {c.dtype}')

The array c
[ 1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j]
of shape (9,) and data type complex128


### Exercise 8.2

(a) Create an arbitrary one dimensional array called v1.  
(b) Create a new array (or a view) v2 which consists of items with odd indices of v1.  
(c) Create a new array (or a view) v3 in backwards ordering from v1.

In [ ]:
# (a)

v1 = np.arange(10)

print(v1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# (b)

v2 = v1[1::2]   #view

print(v2)

[1 3 5 7 9]


In [ ]:
# (c)

v3 = v1[::-1]   #view

print(v3)

[9 8 7 6 5 4 3 2 1 0]


### Exercise 8.3

(a) Create a two dimensional array called m1, shape=(4,5).  
(b) Create a new array (or a view) m2 from m1, in which the elements of each row are in reverse order.  
(c) Create a new array (or a view) m3 from m1, in which the elements of each column are in reverse order.  
(d) Remove the first row, the last row, the first column, and the last column of m1, and create a new array (or a view) m4.  

In [36]:
m1 = np.arange(20).reshape(4,5)

print(m1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
m2 = m1[::,::-1]    #view

print(m2)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]


In [ ]:
m3 = m1[::-1]   #view

print(m3)

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [ ]:
m4 = m1[1:-1,1:-1]  #view

print(m4)

[[ 6  7  8]
 [11 12 13]]
